import React from 'react'
import Head from 'next/head'
import Layout from '../components/Layout'
import style from '../styles/Home.module.css'
const Auth = () => {
    return (
        <div className={style.container}>
            <Head>
            <title>Strapi E-Commerce | Login</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout >
                <h1>Login</h1>
            </Layout>
        </div>
    )
}

export default Auth
